### ISSUE TITLE
Problem!!!

### ISSUE THREAD

**Issue by mengfanyu-hd** [dotnet/website-feedback#282] opened 2024-11-06 13:58 UTC
### URL

https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/run

### Operating system

macos

### Description

我在使用的时候 无法编译项目文件。![Image](https://github.com/user-attachments/assets/bfca08dc-f554-4c15-9bd6-209fd8f7249f)

**Comment by mairaw** [comment] 2024-11-20 02:32
duplicate of https://github.com/dotnet/website-feedback/issues/280

**Closed by mairaw** 2024-11-20 02:32 UTC
Labels: area-tutorials
