### ISSUE TITLE
'IServerSideBlazorBuilder' does not contain a definition for 'AddInteractiveWebAssemblyComponents' and no accessible extension method 'AddInteractiveWebAssemblyComponents' accepting a first argument of type 'IServerSideBlazorBuilder' could be found (are you missing a using directive or an assembly reference?)	BlazorApp1	C:\Users\new\source\repos\BlazorApp1\BlazorApp1\BlazorApp1\Program.cs	9	Active

### ISSUE THREAD

**Issue by nwaapz** [dotnet/website-feedback#66] opened 2024-02-25 22:50 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

windws 10 - vs 2022

**Comment by mairaw** [comment] 2024-02-26 02:48
Closing as duplicate of #67

**Closed by mairaw** 2024-02-26 02:48 UTC
