### ISSUE TITLE
Problem!!!

### ISSUE THREAD

**Issue by mengfanyu-hd** [dotnet/website-feedback#281] opened 2024-11-06 13:57 UTC
### URL

https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/run

### Operating system

macos

### Description

![Image](https://github.com/user-attachments/assets/73fc40d5-580d-4f8d-9e68-4c33fbd8555a)

**Comment by mairaw** [comment] 2024-11-20 02:32
duplicate of https://github.com/dotnet/website-feedback/issues/280

**Closed by mairaw** 2024-11-20 02:32 UTC
Labels: area-tutorials, needs-triage
