### ISSUE TITLE
正在执行任务: dotnet: build /Users/mengfanyu/Csharp/My project1/Assembly-CSharp.csproj   dotnet build /Users/mengfanyu/Csharp/My project1/Assembly-CSharp.csproj /property:GenerateFullPaths=true /consoleloggerparameters

### ISSUE THREAD

**Issue by mengfanyu-hd** [dotnet/website-feedback#284] opened 2024-11-06 13:59 UTC
### URL

https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/run

### Operating system

macos

### Description

![Image](https://github.com/user-attachments/assets/cdbee8b8-9f38-47ac-ab44-350fb0e296e5)
无法编译

**Comment by mairaw** [comment] 2024-11-20 02:40
duplicate of #280

**Closed by mairaw** 2024-11-20 02:40 UTC
Labels: area-tutorials, needs-triage
