### ISSUE TITLE
I don't use Visual Studio

### ISSUE THREAD

**Issue by fabricio-p** [dotnet/website-feedback#272] opened 2024-10-26 18:32 UTC
### URL

https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install

### Operating system

Linux

### More information about your system

Linux 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Description

I don't use Visual Studio (Code) and it would be great if the tutorial provided some way of setting up with just the `dotnet` CLI command.

### dotnet --info

.NET SDK:
 Version:           8.0.110
 Commit:            87a66bb3d1
 Workload version:  8.0.100-manifests.9143487c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/sdk/8.0.110/

.NET workloads installed:
 Workload version: 8.0.100-manifests.9143487c
There are no installed workloads to display.

Host:
  Version:      8.0.10
  Architecture: x64
  Commit:       81cabf2857

.NET SDKs installed:
  8.0.110 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.10 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.10 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by mairaw** [comment] 2024-10-29 03:42
@BethMassi @rachelkang not sure how feasible this is. It seems a very niche scenario. What do you think of this suggestion for Linux? I remember we haven't even added the VS Code version for Linux before by design.

**Comment by BethMassi** [comment] 2024-10-30 18:41
I don't think a getting started via CLI will be that useful for a getting started tutorial because of the many manual steps you'll need to do to get Android set up. We're also not prioritizing MAUI development on Linux at this time. I imagine that if we did create a Linux tutorial, it would be VS Code-focused.

**Comment by claudiaregio** [comment] 2024-12-03 00:24
Closing with no action required at this time

**Closed by claudiaregio** 2024-12-03 00:24 UTC
Labels: area-tutorials
