### ISSUE TITLE
Problem!!!

### ISSUE THREAD

**Issue by mengfanyu-hd** [dotnet/website-feedback#283] opened 2024-11-06 13:58 UTC
### URL

https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/run

### Operating system

macos

### Description

![Image](https://github.com/user-attachments/assets/de793dac-c6dc-4307-9e81-f46296fa0b31)
无法编译项目文件

**Comment by mairaw** [comment] 2024-11-20 02:32
duplicate of #280

**Closed by mairaw** 2024-11-20 02:32 UTC
Labels: duplicate, area-tutorials
