### ISSUE TITLE
dotnet watch can't work

### ISSUE THREAD

**Issue by mcxufly** [dotnet/website-feedback#258] opened 2024-10-03 02:51 UTC
### URL

https://dotnet.microsoft.com/zh-cn/learn/aspnet/blazor-tutorial/run### 

### Operating system

linux

### More information about your system

OS: Arch Linux x86_64
Kernel: 6.11.1-arch1-1

### Description

I create a BlazorApp as the tutorial show, but command `dotnet watch` can't work.
```log
You must install or update .NET to run this application.

App: /usr/share/dotnet/sdk/8.0.402/DotnetTools/dotnet-watch/8.0.402-servicing.24466.16/tools/net8.0/any/dotnet-watch.dll
Architecture: x64
Framework: 'Microsoft.AspNetCore.App', version '8.0.8' (x64)
.NET location: /usr/share/dotnet/

No frameworks were found.

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=8.0.8&arch=x64&rid=arch-x64&os=arch
```

### dotnet --info

.NET SDK:
 Version:           8.0.402
 Commit:            70aa751718
 Workload version:  8.0.400-manifests.2772ffde
 MSBuild version:   17.11.4+37eb419ad

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.402/

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.402 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.NETCore.App 8.0.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by katiesavage** [comment] 2024-10-04 18:15
Can you clarify the method you use to install [.NET on Linux](https://learn.microsoft.com/en-us/dotnet/core/install/linux?WT.mc_id=dotnet-35129-website)?

@danroth27 any ideas?

**Comment by danroth27** [comment] 2024-10-04 19:18
My best guess is some step was missed when installing the .NET SDK. Once we hear back on how the install was, done we can try to reproduce the issue.

**Comment by danroth27** [comment] 2024-10-04 21:34
Actually, I investigated this with @richlander, and it looks like on Arch Linux you need to install the ASP.NET Core runtime separately using the [aspnet-runtime](https://archlinux.org/packages/extra/x86_64/aspnet-runtime/) package. @mcxufly Can you give that a try?: `pacman -Sy aspnet-runtime`. 

@richlander We should probably update our [Install .NET on Linux](https://learn.microsoft.com/dotnet/core/install/linux) with some instructions on how to get set up on Arch Linux.

**Comment by richlander** [comment] 2024-10-04 21:40
For clarity, the following command will install .NET SDK, ASP.NET Core, and .NET runtime.

```bash
sudo pacman -Sy dotnet-sdk aspnet-runtime
```

**Comment by mcxufly** [comment] 2024-10-06 02:14
@katiesavage I use pacman installed dotnet-sdk. I do not install package aspnet-runtime. I will install it and try again.
And thanks a lot @richlander @danroth27 .

**Comment by mcxufly** [comment] 2024-10-06 02:18
I installed package aspnet-runtime, the blazor app run correctly.
I think package aspnet-runtime should be mentioned in [install page](https://dotnet.microsoft.com/zh-cn/learn/aspnet/blazor-tutorial/install)
Thanks a lot again!

**Comment by katiesavage** [comment] 2024-10-07 16:59
I'm glad this helped! Closing this issue now 🙂

**Comment by mairaw** [comment] 2024-10-08 17:08
Closing. We have https://github.com/dotnet/docs/issues/42849 tracking the docs issue.

**Closed by mairaw** 2024-10-08 17:08 UTC
Labels: area-tutorials, tutorial-blazor
